"""asset library + preplan elements

Revision ID: 17b22dbf802c
Revises: 3a077842edbd
Create Date: 2026-07-21 21:54:51.727550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17b22dbf802c'
down_revision = '3a077842edbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('filename', sa.String(length=300), nullable=True),
    sa.Column('original_name', sa.String(length=300), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_uploaded_at'), ['uploaded_at'], unique=False)

    op.create_table('preplan_element',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occupancy_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('caption', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['occupancy_id'], ['occupancy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('preplan_element', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_preplan_element_occupancy_id'), ['occupancy_id'], unique=False)

    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.add_column(sa.Column('element_sequence', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.drop_column('element_sequence')

    with op.batch_alter_table('preplan_element', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_preplan_element_occupancy_id'))

    op.drop_table('preplan_element')
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_uploaded_at'))
        batch_op.drop_index(batch_op.f('ix_asset_department_id'))

    op.drop_table('asset')
    # ### end Alembic commands ###
