"""roles superuser + officer, commanding officer, review policy + fields

Revision ID: 2f62f23a8dc4
Revises: a5f55195273e
Create Date: 2026-07-22 10:18:36.417889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f62f23a8dc4'
down_revision = 'a5f55195273e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commanding_officer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_commanding_officer', 'app_user', ['commanding_officer_id'], ['id'])

    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.add_column(sa.Column('officer_review_policy', sa.String(length=20), server_default='commanding_officer', nullable=False))

    with op.batch_alter_table('occupancy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('review_note', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_occupancy_reviewed_by', 'app_user', ['reviewed_by_id'], ['id'])

    # ### end Alembic commands ###

    # Data backfill: every department gets one superuser (the "chief").
    conn = op.get_bind()
    # 1. Anyone holding rank "Chief" becomes the superuser.
    conn.execute(sa.text("UPDATE app_user SET role='superuser' WHERE rank='Chief'"))
    # 2. Departments still without a superuser: promote the earliest admin (else the
    #    earliest user). `role <> 'admin'` sorts admins first (0), then by id.
    dept_ids = [r[0] for r in conn.execute(sa.text("SELECT id FROM department"))]
    for did in dept_ids:
        if conn.execute(sa.text(
            "SELECT 1 FROM app_user WHERE department_id=:d AND role='superuser' LIMIT 1"
        ), {"d": did}).first():
            continue
        row = conn.execute(sa.text(
            "SELECT id FROM app_user WHERE department_id=:d "
            "ORDER BY (role <> 'admin'), id LIMIT 1"
        ), {"d": did}).first()
        if row:
            conn.execute(sa.text("UPDATE app_user SET role='superuser' WHERE id=:i"),
                         {"i": row[0]})


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occupancy', schema=None) as batch_op:
        batch_op.drop_constraint('fk_occupancy_reviewed_by', type_='foreignkey')
        batch_op.drop_column('review_note')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('reviewed_by_id')

    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.drop_column('officer_review_policy')

    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_commanding_officer', type_='foreignkey')
        batch_op.drop_column('commanding_officer_id')

    # ### end Alembic commands ###
