"""preplan review fields + announcements

Revision ID: 3a077842edbd
Revises: ef4f05e9cb92
Create Date: 2026-07-21 13:41:28.432813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a077842edbd'
down_revision = 'ef4f05e9cb92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_announcement_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcement_department_id'), ['department_id'], unique=False)

    with op.batch_alter_table('occupancy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        # server_default backfills existing pre-plans to "draft"; new rows use the
        # model's Python-side default.
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False,
                                      server_default="draft"))
        batch_op.add_column(sa.Column('submitted_to_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('submitted_at', sa.DateTime(), nullable=True))
        # SQLite batch mode requires named constraints.
        batch_op.create_foreign_key('fk_occupancy_submitted_to', 'app_user', ['submitted_to_id'], ['id'])
        batch_op.create_foreign_key('fk_occupancy_created_by', 'app_user', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occupancy', schema=None) as batch_op:
        batch_op.drop_constraint('fk_occupancy_created_by', type_='foreignkey')
        batch_op.drop_constraint('fk_occupancy_submitted_to', type_='foreignkey')
        batch_op.drop_column('submitted_at')
        batch_op.drop_column('submitted_to_id')
        batch_op.drop_column('status')
        batch_op.drop_column('created_by')

    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcement_department_id'))
        batch_op.drop_index(batch_op.f('ix_announcement_created_at'))

    op.drop_table('announcement')
    # ### end Alembic commands ###
