"""Add tile-layer kind, attribution, max_zoom to overlays

Revision ID: 7ed1629efb9d
Revises: a361c72e8074
Create Date: 2026-07-20 10:05:21.852388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ed1629efb9d'
down_revision = 'a361c72e8074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wms_layer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.String(length=8), nullable=False,
                                      server_default='wms'))
        batch_op.add_column(sa.Column('attribution', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('max_zoom', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wms_layer', schema=None) as batch_op:
        batch_op.drop_column('max_zoom')
        batch_op.drop_column('attribution')
        batch_op.drop_column('kind')

    # ### end Alembic commands ###
