"""add user special_role

Revision ID: 82a7f5c8f620
Revises: da1e62bf7df1
Create Date: 2026-07-23 14:34:45.754157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82a7f5c8f620'
down_revision = 'da1e62bf7df1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('special_role', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.drop_column('special_role')

    # ### end Alembic commands ###
