"""Add MapFeature.symbol and User.rank

Revision ID: 8909d0017641
Revises: 7ed1629efb9d
Create Date: 2026-07-20 11:47:10.006328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8909d0017641'
down_revision = '7ed1629efb9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank', sa.String(length=40), nullable=True))

    with op.batch_alter_table('map_feature', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symbol', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map_feature', schema=None) as batch_op:
        batch_op.drop_column('symbol')

    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.drop_column('rank')

    # ### end Alembic commands ###
