"""offline sync: uuid, updated_at, deletion tombstones

Revision ID: a361c72e8074
Revises: a445699384d9
Create Date: 2026-07-19 10:01:15.536317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a361c72e8074'
down_revision = 'a445699384d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deletion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deletion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deletion_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_deletion_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deletion_uuid'), ['uuid'], unique=False)

    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_contact_uuid'), ['uuid'], unique=True)

    with op.batch_alter_table('hazard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_hazard_uuid'), ['uuid'], unique=True)

    with op.batch_alter_table('hydrant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_hydrant_uuid'), ['uuid'], unique=True)

    with op.batch_alter_table('map_feature', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_map_feature_uuid'), ['uuid'], unique=True)

    with op.batch_alter_table('occupancy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_occupancy_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###

    # --- data backfill: existing rows need a unique uuid + an updated_at ------
    import uuid as _uuid
    from datetime import datetime, timezone
    bind = op.get_bind()
    now = datetime.now(timezone.utc).replace(tzinfo=None)
    tables = ("occupancy", "contact", "hazard", "hydrant", "map_feature")
    for table in tables:
        ids = [row[0] for row in bind.execute(
            sa.text(f"SELECT id FROM {table} WHERE uuid IS NULL"))]
        for rid in ids:
            bind.execute(
                sa.text(f"UPDATE {table} SET uuid = :u WHERE id = :i"),
                {"u": str(_uuid.uuid4()), "i": rid})
    for table in tables:
        bind.execute(
            sa.text(f"UPDATE {table} SET updated_at = :now WHERE updated_at IS NULL"),
            {"now": now})


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occupancy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_occupancy_uuid'))
        batch_op.drop_column('uuid')

    with op.batch_alter_table('map_feature', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_map_feature_uuid'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('uuid')

    with op.batch_alter_table('hydrant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hydrant_uuid'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('uuid')

    with op.batch_alter_table('hazard', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hazard_uuid'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('uuid')

    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_uuid'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('uuid')

    with op.batch_alter_table('deletion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deletion_uuid'))
        batch_op.drop_index(batch_op.f('ix_deletion_department_id'))
        batch_op.drop_index(batch_op.f('ix_deletion_deleted_at'))

    op.drop_table('deletion')
    # ### end Alembic commands ###
