"""wms_layer overlays

Revision ID: a445699384d9
Revises: cae993d17314
Create Date: 2026-07-18 21:42:16.023484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a445699384d9'
down_revision = 'cae993d17314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wms_layer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('layers', sa.String(length=300), nullable=False),
    sa.Column('image_format', sa.String(length=40), nullable=True),
    sa.Column('transparent', sa.Boolean(), nullable=True),
    sa.Column('opacity', sa.Float(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wms_layer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wms_layer_department_id'), ['department_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wms_layer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wms_layer_department_id'))

    op.drop_table('wms_layer')
    # ### end Alembic commands ###
