"""asset ocr_pending flag

Revision ID: a5f55195273e
Revises: 17b22dbf802c
Create Date: 2026-07-21 22:36:23.388048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f55195273e'
down_revision = '17b22dbf802c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        # server_default backfills existing assets to False (already indexed inline).
        batch_op.add_column(sa.Column('ocr_pending', sa.Boolean(), nullable=False,
                                      server_default=sa.false()))
        batch_op.create_index(batch_op.f('ix_asset_ocr_pending'), ['ocr_pending'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_ocr_pending'))
        batch_op.drop_column('ocr_pending')

    # ### end Alembic commands ###
