"""Add MapFeature.rotation for arrow symbols

Revision ID: baeb6c30d19d
Revises: 8909d0017641
Create Date: 2026-07-20 12:28:29.412301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baeb6c30d19d'
down_revision = '8909d0017641'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map_feature', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rotation', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map_feature', schema=None) as batch_op:
        batch_op.drop_column('rotation')

    # ### end Alembic commands ###
