"""Add MapFeature label position

Revision ID: c6e55c0422d8
Revises: c9e338b81060
Create Date: 2026-07-20 16:58:23.048044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6e55c0422d8'
down_revision = 'c9e338b81060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map_feature', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('label_lng', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map_feature', schema=None) as batch_op:
        batch_op.drop_column('label_lng')
        batch_op.drop_column('label_lat')

    # ### end Alembic commands ###
