"""Add MapFeature scale and length for arrows

Revision ID: c9e338b81060
Revises: baeb6c30d19d
Create Date: 2026-07-20 16:43:26.231843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9e338b81060'
down_revision = 'baeb6c30d19d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map_feature', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scale', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('length', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map_feature', schema=None) as batch_op:
        batch_op.drop_column('length')
        batch_op.drop_column('scale')

    # ### end Alembic commands ###
