"""initial schema with auth and multi-tenancy

Revision ID: cae993d17314
Revises: 
Create Date: 2026-07-18 20:56:39.785594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cae993d17314'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_user_email'), ['email'], unique=True)

    op.create_table('hydrant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('flow_gpm', sa.Integer(), nullable=True),
    sa.Column('static_pressure', sa.Integer(), nullable=True),
    sa.Column('residual_pressure', sa.Integer(), nullable=True),
    sa.Column('size_inches', sa.String(length=40), nullable=True),
    sa.Column('hydrant_type', sa.String(length=80), nullable=True),
    sa.Column('in_service', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hydrant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hydrant_department_id'), ['department_id'], unique=False)

    op.create_table('occupancy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('footprint_geojson', sa.Text(), nullable=True),
    sa.Column('occupancy_type', sa.String(length=80), nullable=True),
    sa.Column('construction_type', sa.String(length=80), nullable=True),
    sa.Column('stories', sa.Integer(), nullable=True),
    sa.Column('square_footage', sa.Integer(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('building_condition', sa.String(length=40), nullable=True),
    sa.Column('roof_construction', sa.String(length=200), nullable=True),
    sa.Column('sprinkler_system', sa.Boolean(), nullable=True),
    sa.Column('sprinkler_details', sa.Text(), nullable=True),
    sa.Column('standpipe_system', sa.Boolean(), nullable=True),
    sa.Column('standpipe_details', sa.Text(), nullable=True),
    sa.Column('fire_alarm_system', sa.Boolean(), nullable=True),
    sa.Column('fdc_location', sa.String(length=200), nullable=True),
    sa.Column('knox_box_location', sa.String(length=200), nullable=True),
    sa.Column('gate_code', sa.String(length=80), nullable=True),
    sa.Column('alarm_pin', sa.String(length=80), nullable=True),
    sa.Column('annunciator_location', sa.String(length=200), nullable=True),
    sa.Column('electric_shutoff_location', sa.String(length=200), nullable=True),
    sa.Column('gas_shutoff_location', sa.String(length=200), nullable=True),
    sa.Column('water_shutoff_location', sa.String(length=200), nullable=True),
    sa.Column('water_supply_notes', sa.Text(), nullable=True),
    sa.Column('hazards_summary', sa.Text(), nullable=True),
    sa.Column('access_notes', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('occupancy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_occupancy_department_id'), ['department_id'], unique=False)

    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occupancy_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['occupancy_id'], ['occupancy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('floor_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occupancy_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('image_filename', sa.String(length=300), nullable=True),
    sa.Column('annotations_json', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['occupancy_id'], ['occupancy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hazard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occupancy_id', sa.Integer(), nullable=False),
    sa.Column('hazard_type', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['occupancy_id'], ['occupancy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('map_feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('occupancy_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('geometry_json', sa.Text(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['occupancy_id'], ['occupancy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('map_feature', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_map_feature_department_id'), ['department_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map_feature', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_map_feature_department_id'))

    op.drop_table('map_feature')
    op.drop_table('hazard')
    op.drop_table('floor_plan')
    op.drop_table('contact')
    with op.batch_alter_table('occupancy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_occupancy_department_id'))

    op.drop_table('occupancy')
    with op.batch_alter_table('hydrant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hydrant_department_id'))

    op.drop_table('hydrant')
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_user_email'))

    op.drop_table('app_user')
    op.drop_table('department')
    # ### end Alembic commands ###
