"""rank_edit_policy + password_reset_code

Revision ID: da1e62bf7df1
Revises: 2f62f23a8dc4
Create Date: 2026-07-22 18:41:13.633899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da1e62bf7df1'
down_revision = '2f62f23a8dc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name='fk_reset_code_user'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_code', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_code_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank_edit_policy', sa.String(length=20), server_default='admins', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.drop_column('rank_edit_policy')

    with op.batch_alter_table('password_reset_code', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_code_user_id'))

    op.drop_table('password_reset_code')
    # ### end Alembic commands ###
