"""add department.is_sandbox

Revision ID: ef4f05e9cb92
Revises: c6e55c0422d8
Create Date: 2026-07-21 06:36:09.911310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef4f05e9cb92'
down_revision = 'c6e55c0422d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department', schema=None) as batch_op:
        # server_default backfills existing rows to False (NOT NULL); new rows use
        # the model's Python-side default.
        batch_op.add_column(sa.Column('is_sandbox', sa.Boolean(), nullable=False,
                                      server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.drop_column('is_sandbox')

    # ### end Alembic commands ###
